# Generated by Django 4.2.28 on 2026-02-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='电话')),
                ('kindergarten', models.CharField(max_length=100, verbose_name='园所名称')),
                ('city', models.CharField(max_length=50, verbose_name='城市')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
            ],
            options={
                'verbose_name': '预约演示',
                'verbose_name_plural': '预约演示',
            },
        ),
    ]
