# Generated by Django 4.2.28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchemeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="姓名")),
                ("phone", models.CharField(max_length=20, verbose_name="电话")),
                (
                    "kindergarten",
                    models.CharField(max_length=100, verbose_name="园所名称"),
                ),
                ("city", models.CharField(max_length=50, verbose_name="城市")),
                (
                    "demand",
                    models.TextField(
                        help_text="想索取哪些方案/资料", verbose_name="索取内容"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="是否已处理"),
                ),
                ("note", models.TextField(blank=True, default="", verbose_name="备注")),
            ],
            options={
                "verbose_name": "索取方案",
                "verbose_name_plural": "索取方案",
            },
        ),
    ]
