# Generated by Django 4.2.28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_add_schemerequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="DownloadLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="下载时间"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="姓名")),
                ("phone", models.CharField(max_length=20, verbose_name="电话")),
                (
                    "kindergarten",
                    models.CharField(max_length=100, verbose_name="园所名称"),
                ),
                ("city", models.CharField(max_length=50, verbose_name="城市")),
                (
                    "product_name",
                    models.CharField(max_length=100, verbose_name="产品名"),
                ),
                ("file_name", models.CharField(max_length=255, verbose_name="文件名")),
                (
                    "file_type",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="文件类型"
                    ),
                ),
                (
                    "file_path",
                    models.CharField(max_length=500, verbose_name="文件路径"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, default="", verbose_name="User-Agent"),
                ),
            ],
            options={
                "verbose_name": "资料下载记录",
                "verbose_name_plural": "资料下载记录",
            },
        ),
    ]
